version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/project/public:cached
    links:
      - invest
    networks:
      - frontend
  invest:
    build: ./
    volumes:
      - ./:/project:cached
    working_dir: /project
    networks:
      - frontend
      - backend
    environment:
      APP_ENV: local
      APP_KEY: "base64:05VNDWbv5axaVCzWrtTBLMV1T1Ex8ML4dNzWINrWXHY="
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: investdb
      DB_USERNAME: root
      DB_PASSWORD: invest_password
  mysql:
    image: mysql:8.0.17
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: investdb
      MYSQL_ROOT_PASSWORD: invest_password
    volumes:
      - ./:/project:ro
    working_dir: /project
    networks:
      - backend
  node:
    image: node:8.12
    volumes:
      - ./:/project:cached
    working_dir: /project
    command: tail -F anything

networks:
  frontend:
  backend:
